# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

<script type="application/javascript" src="chrome://global/content/globalOverlay.js"/>

<!-- Code that is common to both webappWindow.xul and hiddenWindow.xul. -->
<script type="application/javascript" src="chrome://webapprt/content/window.js"/>
